### ISSUE TITLE
Need more description to run this script

### ISSUE THREAD

**Issue by wardensc2** [NotTheStallion/Re-shard_Safetensors#1]
Hi @NotTheStallion 

I try to run your script but I get error from install your requirement.txt. Can you support me how to run this script in detail. I use only windows and dont have much knowledge about Python

![image](https://github.com/user-attachments/assets/9860f2b5-62ba-4934-8034-10887b349f45)

**Comment by NotTheStallion** [comment]
Hello @wardensc2 ,

My code was made to support Linux machines. 
I suggest you install Windows Subsystem for Linux (WSL) and then run the `pip install -r requirements.txt`.

Guide : https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by pivtienduc** [comment]
> Hello @wardensc2 ,
> 
> My code was made to support Linux machines. I suggest you install Windows Subsystem for Linux (WSL) and then run the `pip install -r requirements.txt`.
> 
> Guide : https://learn.microsoft.com/en-us/windows/wsl/install

Hi @NotTheStallion 

Thank for your quick answer, I'm looking for a tool just to do some quick merging, my demand is not so much, I just need to merge 1 time, do you know some online service that can do it. To install the whole Linux to merge just 1 time is a bit too much.

**Comment by NotTheStallion** [comment]
Sadly, i made this code because i couldn't find online service that does it for me.
In that case, i suggest you try to install the needed packages in the vscode terminal in hope it works.
